### ISSUE TITLE
Not able to pull publication title from Hashnode

### ISSUE THREAD

**Issue by rishi-raj-jain** [MatthiesenXYZ/astro-hashnode#21]
**Describe the bug**

Not able to use `astro-hashnode` from the steps mentioned in the README.md

**To Reproduce**

- npm create astro@latest
- follow along the CLI prompts with TS enabled
- npm run astro add @matthiesenxyz/astro-hashnode in the project
- use the example URL it provided in README.md
- wait for Astro-Hashnode Integration Setup Complete to appear
- open the project on 4321 but it says not found title of the publication data

**Expected behavior**

It pulls the data correctly or shows a warning/steps of what to be done.

**Screenshots**
![image](https://github.com/MatthiesenXYZ/astro-hashnode/assets/46300090/d7e25e19-f1a3-4241-86ea-67703b9caa75)
<img width="1512" alt="Screenshot 2024-03-15 at 3 42 46 PM" src="https://github.com/MatthiesenXYZ/astro-hashnode/assets/46300090/2a69c748-4f61-47ee-9885-f704ed8ac023">

**Comment by Adammatthiesen** [comment]
@rishi-raj-jain can you try taking the `https://` off the domain url?(GraphQL really does not like http:// or https://... as well as add `verbose: true` to show the full output. in the first photo the vite warnings look like your local instance has been looping... if thats true those warnings can be ignored.

**Comment by rishi-raj-jain** [comment]
@Adammatthiesen

Would we able to enforce the removal of https?

**Comment by rishi-raj-jain** [comment]
https://github.com/MatthiesenXYZ/astro-hashnode/blob/main/package/src/schemas/user-config.ts#L12

we can update the zod configuration to throw an error if it doesn't matches the URL pattern the package requires.

what do you think?

**Comment by Adammatthiesen** [comment]
The new PR I just setup, adds the ability to handle that, using functions to remove the http, or https from the string.

**Comment by Adammatthiesen** [comment]
@rishi-raj-jain Newest update should resolve that issue!
